### PR TITLE
fix: run example error in xcode

### PR DESCRIPTION
**Pull request by Jamlee**
## Summary
Under the current circumstances, Example cannot run because the files in AuroraEditorSourceEditor seem to have only been modified halfway, some are called AuroraEditorSourceEditorExample, and some are called CodeEditorSourceEditor. I changed the whole thing to AuroraEditorSourceEditorExample and it runs through on Xcode 15.

## Changes Made
1. The Example directory compiles through as a whole.
2. The LanguagePicker in Example cannot echo back because CodeLanguage always defaults to false when compared.
3.  textViewDidChange must be public

## TODO

none

## Motivation

Run the Example normally to understand more intuitively the principle of implementing an editor with SwiftUI

## Testing

none

## Screenshots/GIFs

image

## Checklist

Please ensure all of the following are completed before submitting the PR:
- [x] Code has been tested and verified.
- [ ] Documentation has been updated to reflect the changes.
- [ ] All tests pass successfully.
- [ ] Code follows the project's coding guidelines and style.
- [x] The branch is up-to-date with the latest changes from the main branch.
- [ ] Reviewed by at least one other contributor.

## Related Issues
none

## Additional Notes
none

### CODE REVIEW

**Comment by aurora-care-bear** [comment]
Thanks for submitting a pull request!
We will review it as soon as possible.

**Comment by Jamlee** [comment]
@nanashili hello,  Would you please review the code? 😄

**Review by nanashili — APPROVED** [review]
Lgtm

**Comment by aurora-care-bear** [comment]
Hey @Jamlee,

Thanks for your contribution.
Your PR has been merged!
Your name will appear on https://auroraeditor.com/#contributors in a few moments, if you have contributed to the editor.

Thanks again for your contribution!

Kind Regards,
Aurora Editor Team.

**Pull request merged**
